### PR TITLE
Maintain correct source order even when receiving new chapters from a sync service

### LINKED ISSUE #1339: Order of chapters wrong when received through sync
### Steps to reproduce

Precondition: Device A: Has new chapters not on Device B

1. Device A synchronizes
2. Device B synchronizes
3. View entry with new chapters received through sync (not standard update)

### Expected behavior

Chapters are in correct order.

### Actual behavior

They get mixed in with the latest chapter usually ending up at the next one.

### Crash logs

_No response_

### TachiyomiSY version

r574

### Android version

Android 15 (OxygenOS 15.0)

### Device

OnePlus Pad 2

### Other details

**Edit: I'm using SyncYomi self-hosted** (forgot to also note this down, but I also had this issue on Google Drive before migrating)

Paste from the settings: 

App version: 1.11.0 (standard, 26cfb4811, 71, 2024-11-08T03:25:38Z)
Preview build: 574
Android version: 15 (SDK 35; build OPD2403_15.0.0.202(EX01))
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OP5DAAL1 (OPD2403EEA)
Device model: OPD2403
WebView: Android System WebView 131.0.6778.39

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Lolle2000la**
**Fixes #1339**

#### Problem description and origin

If chapters are pushed to a sync service from Device A and these new chapters are then received by Device B, the source order of these chapters will be wrong because the existing chapters have not gotten their source order adjusted. This source order usually changes when new chapters get added or old ones get removed, however, as-is local chapters will still be in the order of before with the new chapters now colliding with the old chapters (leading to orders like "Chapter 38" -> "Chapter 43" -> "Chapter 37" -> "Chapter 42" -> ...).

#### How this PR fixes the problem

The proposed changes now ensure that this corner case for syncing is caught and the `sourceOrder` of the chapters are now in the correct order. I made it so that existing behavior not sync-related should remain unaffected.

#### Screenshot illustrating the problem

393552769-3519cc72-ca2d-4d0d-9144-0cc6e6b45288 - Copy

### CODE REVIEW

**Review by jobobby04 — APPROVED** [review]

File: app/src/main/java/eu/kanade/tachiyomi/data/backup/restore/restorers/MangaRestorer.kt [hunk 1]
```diff
@@ -202,6 +202,7 @@ class MangaRestorer(
                 bookmark = chapter.bookmark || dbChapter.bookmark,
                 read = chapter.read,
                 lastPageRead = chapter.lastPageRead,
+                sourceOrder = chapter.sourceOrder
```
Comment (Lolle2000la) [inline app/src/main/java/eu/kanade/tachiyomi/data/backup/restore/restorers/MangaRestorer.kt:205]: If I understand correctly, the build failed because a comma should be at the end here?

Comment (Lolle2000la) [reply app/src/main/java/eu/kanade/tachiyomi/data/backup/restore/restorers/MangaRestorer.kt]: Seems to have been it

**Comment by jobobby04** [comment]
It was a lint error, you can run the automatic formatter by doing `./gradlew :app:spotlessApply` which should fix all those.

**Comment by Lolle2000la** [comment]
> It was a lint error, you can run the automatic formatter by doing `./gradlew :spotlessApply` which should fix all those.

`./gradlew :spotlessApply` didn't work but `./gradlew spotlessApply` did, just if someone else stumbles upon this (most likely me).

**Comment by jobobby04** [comment]
I always forget if it needs the `:` before the task 😄

**Comment by Lolle2000la** [comment]
Just in case someone stumbles upon this for unrelated reasons, I am now using the following git pre-commit hook, which works on both Windows and Linus and should make sure no commits get made in an invalid state:

```sh
#!/bin/bash

echo "Running pre-commit hook on Windows."

# Navigate to the repository root directory temporarily.
REPO_ROOT=$(git rev-parse --show-toplevel)
pushd "$REPO_ROOT" >/dev/null || {
  echo "Failed to change directory to repository root. Aborting pre-commit hook."
  exit 1
}

# Capture the output of the Gradle spotlessApply task.
OUTPUT=$(./gradlew spotlessApply 2>&1)
EXIT_CODE=$?

# Stage all changes made by spotlessApply.
git add -u

# Restore the original directory
popd >/dev/null

if [ $EXIT_CODE -ne 0 ]; then
  echo "spotlessApply failed. Aborting commit."
  echo "$OUTPUT"
  exit $EXIT_CODE
fi

echo "spotlessApply completed successfully. Proceeding with commit."
```
