### PR TITLE
Respect the `altTitlesInDesc` preference (MD)

### LINKED ISSUE #903: MangaDex alternative titles in description not working
### Steps to reproduce

https://github.com/tachiyomiorg/tachiyomi-extensions/pull/16607 has added appending alternative titles to the description of the manga.

### Expected behavior

When the setting is enabled, it should append the alternative titles upon updating the entry.

### Actual behavior

With TachiyomiSY it does not append the alternative titles.
In Tachiyomi it does append the alt titles.

### Crash logs

_No response_

### Tachiyomi version

Preview r552

### Android version

Android 11

### Device

Lenovo Tab P11

### Other details

_No response_

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by NGB-Was-Taken**
Closes #903

### CODE REVIEW

File: app/src/main/java/exh/md/utils/MdUtil.kt [hunk 1]
```diff
@@ -256,5 +256,15 @@ class MdUtil {
             return jsonParser.encodeToString(body)
                 .toRequestBody("application/json".toMediaType())
         }
+
+        fun addAltTitleToDesc(description: String, altTitles: List<String>?): String {
+            return if (altTitles.isNullOrEmpty()) {
+                description
+            } else {
+                val altTitlesDesc = altTitles
+                    .joinToString("\n", "Alternative Titles:\n") { "• $it" }
```
Comment (NGB-Was-Taken) [inline app/src/main/java/exh/md/utils/MdUtil.kt:265]: Does the "Alternative Titles" text need to be localized in the available MangaDex languages? If yes, how?

Comment (cuong-tran) [reply app/src/main/java/exh/md/utils/MdUtil.kt:265]: put it into strings.xml so it can be translated

Comment (jobobby04) [reply app/src/main/java/exh/md/utils/MdUtil.kt:265]: You can do a `Injekt.get<Application>.getString()` to get the translatable string

**Review by jobobby04 — APPROVED** [review]
